const cards = [
  {
    img: 'images/antez.jpg',
    subtitle: 'Performace/Cognitive WORKSHOP',
    title: 'ACUSTIC SOUND PICTURES',
    teaser:
      'sympathies of the room`s resonant structure/acoustics generated by the movements of the body/investigative process of the acoustic qualities of the performance space',
  },
  {
    img: 'images/live-sessions.jpg',
    subtitle: 'Recording sessions & Live performace',
    title: 'Phantom Orchestra',
    teaser:
      'In collaboration with Bulza Records and featuring over 40 improvisational artists, Bojken Lako presents »Phantom Orchestra,« an archival project of solo improvisational recordings and an unconventional performance developed in the context of pandemic lockdowns.',
  },
  {
    img: 'images/soundspace.png',
    subtitle: 'City-wide Partner Program',
    title: 'Tolla',
    teaser:
      "Tolla is an initiative by Tirana Art Lab and Bulza Festival that aims to showcase the richness and diversity of Tirana's independent project spaces and artist initiatives active in music and sound, visual and media arts, as well as connected hybrid fields. Uniting over 65 initiatives this year, the programme will run parallel to both festivals.",
  },
  {
    img: 'images/antez3.jpg',
    subtitle: 'Commissioned works exploring hybrid radio possibilities',
    title: 'Bulza Radio Lab',
    teaser:
      'Winning projects by Antez, Alba D with Wendy M, and Gine (Continuum) will premiere at BULZA. The commissioned new works explore the intersection of radio with live or generative installation mediums within the context of the festival’s Contact theme.',
  },
  {
    img: 'images/dance.jpg',
    subtitle: 'An interactive dissection of human spirit',
    title: 'Human ways',
    teaser:
      'Combining dance, theatre, interactive music, body art, and biotechnological installation, »Humane Methods « is a living biome that takes shape as a collective, durational experiment in four episodes. Created by Tirana-based performing arts group Lauraanitas (Laura Anita, Emi V, Daniel Z).',
  },
  {
    img: 'images/videos.jpg',
    subtitle: 'Commissioned video series',
    title: 'Kafshet',
    teaser:
      'Launched at Bulza 2021, this two-part series will conclude at our 2022 edition and features multi-disciplinary casts of artists exploring remote collaboration.',
  },
];

const container = document.querySelector('.feature-container');
for (let k = 0; k < cards.length; k += 1) {
  const featureProject = document.createElement('div');
  featureProject.className = 'featWrap';
  console.log(featureProject)
  let featureContent = '';
  featureContent = `
<div class="feature">
  <img class="fImg"src=${cards[k].img} alt="${cards[k].title}">
       <div class="f-text-wrapper">
         <div class="subtitle">${cards[k].subtitle}</div>
            <div class="title">${cards[k].title}</div>
            <div class="f-line">
            <div class="teaser-wrapper">
                 <div class="teaser">
                     <p class="teaser-text">${cards[k].teaser}</p>
                 </div>
            </div>
</div>`;

  featureProject.innerHTML = featureContent;
  container.appendChild(featureProject);
}

/// //hamburger menu///////////////////
const hamburger = document.querySelector('.menu-button');
const closebtn = document.querySelector('.closebtn');
const overlay = document.querySelector('.overlay');
const common = document.querySelectorAll('.common');

function openMenu() {
  overlay.classList.remove('hidden');
}

function closeMenu() {
  overlay.classList.add('hidden');
}

closebtn.addEventListener('click', closeMenu);
hamburger.addEventListener('click', openMenu);

for (let i = 0; i < common.length; i += 1) {
  common[i].addEventListener('click', closeMenu);
}
